#
# This workflow is only run when a PR is merged
# The developers specify a version in the poetry toml file or it has already been bumped from a previous run
# This version is used to create and push a git tag
# A docker image gets built and tagged
# The master branch is then checked out
# We then patch and commit the version in poetry, ready for the next PR. This step is important, it
# will save developers time and will also avoid failing merges because of duplicate git tags
#
#
name: Deploy to AWS ECR

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - .github/workflows/ecr_push.yml
      - "main.py"
      - pyproject.toml
#  push:
#    branches: [feat/**]
#    paths:
#      - .github/workflows/ecr_push.yml
#      - pyproject.toml
#      - main.py

jobs:
  build_push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry config virtualenvs.in-project false
          poetry config installer.parallel true

      - name: Extract service version
        run: |
          echo "DATA_PROVIDER_VERSION=$(poetry version --short)" >> $GITHUB_ENV
          echo "$(poetry version --short)"

      - name: Push git tag version
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git tag -a ${{ env.DATA_PROVIDER_VERSION }} -m "${{ env.DATA_PROVIDER_VERSION }}"
          git push origin ${{ env.DATA_PROVIDER_VERSION }}

      # this will need to be updated to master
#      - name: Checkout main branch
#        uses: actions/checkout@v3
#        with:
#          ref: main

      - name: Bump version with patch ready for next run
        run: |
          poetry version --short patch
          echo "DATA_PROVIDER_VERSION_PATCHED=$(poetry version --short)" >> $GITHUB_ENV
          echo "$(poetry version --short)"
          git status

      - name: Commit patched semantic version ready for next run
        uses: EndBug/add-and-commit@v9.1.0
        with:
          add: "pyproject.toml"
          author_name: github_actor
          default_author: github_actor
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "github action has patched version to ${{ env.DATA_PROVIDER_VERSION_PATCHED }}"

